In [57]:
from google.colab import drive
drive.mount('gdrive')

Drive already mounted at gdrive; to attempt to forcibly remount, call drive.mount("gdrive", force_remount=True).


In [58]:
import pandas as pd
import numpy as np

In [59]:
dataframe = pd.read_csv('gdrive/MyDrive/gowalla/Gowalla_totalCheckins.txt', delimiter = '\t', header = None)

In [60]:
dataframe.count()

0    6442892
1    6442892
2    6442892
3    6442892
4    6442892
dtype: int64

In [61]:
dataframe.head()

0                     1          2          3        4
0  0  2010-10-19T23:55:27Z  30.235909 -97.795140    22847
1  0  2010-10-18T22:17:43Z  30.269103 -97.749395   420315
2  0  2010-10-17T23:42:03Z  30.255731 -97.763386   316637
3  0  2010-10-17T19:26:05Z  30.263418 -97.757597    16516
4  0  2010-10-16T18:50:42Z  30.274292 -97.740523  5535878

In [62]:
dataframe = dataframe.drop(columns= 1)

In [63]:
dataframe.columns = ['User', 'Latitude', 'Longitude', 'Location id']
dataframe

User   Latitude  Longitude  Location id
0             0  30.235909 -97.795140        22847
1             0  30.269103 -97.749395       420315
2             0  30.255731 -97.763386       316637
3             0  30.263418 -97.757597        16516
4             0  30.274292 -97.740523      5535878
...         ...        ...        ...          ...
6442887  196578  51.742988  -0.488065       906885
6442888  196578  51.746492  -0.490780       965121
6442889  196578  51.741916  -0.496729      1174322
6442890  196585  50.105516   8.571525       471724
6442891  196585  50.027812   8.785098      4555073

[6442892 rows x 4 columns]

In [64]:
df = dataframe.drop_duplicates('Location id')
df

User   Latitude  Longitude  Location id
0             0  30.235909 -97.795140        22847
1             0  30.269103 -97.749395       420315
2             0  30.255731 -97.763386       316637
3             0  30.263418 -97.757597        16516
4             0  30.274292 -97.740523      5535878
...         ...        ...        ...          ...
6442859  196577  51.521618  -0.148219      1111497
6442860  196577  51.883750  -1.757373      1044625
6442861  196577  51.917208  -0.660990       845387
6442865  196578  51.712110  -0.050458      1341442
6442891  196585  50.027812   8.785098      4555073

[1280969 rows x 4 columns]

In [65]:
from sklearn import datasets
from sklearn.model_selection import train_test_split
df = df.sample(n=1000)
X, y = df[["User","Latitude","Longitude"]], df["Location id"]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=1)

In [50]:
!pip install diffprivlib

In [76]:
from diffprivlib.models import GaussianNB
clf1 = GaussianNB(epsilon=3)
clf1.fit(X_train, y_train)
clf1.predict(X_test)

/usr/local/lib/python3.7/dist-packages/diffprivlib/models/naive_bayes.py:102: PrivacyLeakWarning: Bounds have not been specified and will be calculated on the data provided. This will result in additional privacy leakage. To ensure differential privacy and no additional privacy leakage, specify bounds for each dimension.
  "privacy leakage, specify bounds for each dimension.", PrivacyLeakWarning)


array([1400308,  845624,  778136, 1400308, 1603198,  778136, 1400308,
        845624,  778136,  845624,  845624, 1400308, 1603198, 1603198,
        845624,  845624,  778136,  845624,  845624,  778136,  416590,
        845624,  845624,  845624,  746295,  845624,  845624,  778136,
        845624,  845624,  778136, 1400308, 1154064, 1400308,  778136,
        845624, 1603198, 1400308, 1400308,  845624,  778136, 1400308,
        845624, 1514989,  137568, 1400308, 1603198, 1400308,  845624,
        845624, 1254731,  845624,  845624,  778136,  255867,  845624,
       1400308, 1400308, 1400308,  845624, 1091525, 1603198,  845624,
        603538,  845624,  845624,  857895, 1400308, 1603198, 1400308,
        242600,  845624,  603538, 1603198,  845624,  778136,  242600,
        416590,  845624, 1603198,  778136,  845624, 1603198,  568007,
        845624,  778136,  845624,  845624,  845624,  778136,  845624,
       1400308,  845624, 1179893,  845624,  845624,  845624,  845624,
        255867, 1400

In [70]:
from diffprivlib.models import LogisticRegression
clf2 = LogisticRegression(epsilon=3)
clf2.fit(X_train, y_train)
clf2.predict(X_test)

/usr/local/lib/python3.7/dist-packages/diffprivlib/models/logistic_regression.py:223: PrivacyLeakWarning: Data norm has not been specified and will be calculated on the data provided.  This will result in additional privacy leakage. To ensure differential privacy and no additional privacy leakage, specify `data_norm` at initialisation.
  "privacy leakage, specify `data_norm` at initialisation.", PrivacyLeakWarning)


array([ 965653,  965653,  965653,  965653,  965653,  965653,  965653,
        965653,  965653,  965653,  937775,  965653,  965653,  965653,
        965653,  965653,  987069,  965653,  937775,  965653,  965653,
        965653,  937775,  965653, 1153600,  965653,  965653,  965653,
        965653,  965653,  965653,  965653,  965653,  965653,  965653,
        937775,  965653,  965653,  965653,  965653,  965653,  965653,
        965653,  965653,  965653,  965653,  965653,  965653,  965653,
        965653,  965653,  965653,  965653,  987069,  965653,  965653,
        965653,  965653,  965653,  965653,  965653,  965653,  965653,
        965653,  965653,  965653,  965653,  965653,  965653,  965653,
        965653,  965653,  965653,  965653,  965653,  965653,  965653,
        965653,  965653,  965653,  965653,  965653,  965653,  965653,
        965653,  987069,  965653,  965653,  965653,  965653,  937775,
        965653,  987069,  965653,  937775,  965653,  937775,  987069,
        965653,  965

In [71]:
from diffprivlib.models import KMeans
clf3 = KMeans(epsilon=3)
clf3.fit(X_train, y_train)
clf3.predict(X_test)

/usr/local/lib/python3.7/dist-packages/diffprivlib/models/k_means.py:131: PrivacyLeakWarning: Bounds have not been specified and will be calculated on the data provided.  This will result in additional privacy leakage. To ensure differential privacy and no additional privacy leakage, specify `bounds` for each dimension.
  "privacy leakage, specify `bounds` for each dimension.", PrivacyLeakWarning)


array([7, 0, 3, 4, 2, 0, 4, 3, 3, 3, 0, 4, 2, 7, 0, 0, 0, 0, 0, 7, 3, 3,
       0, 0, 0, 3, 3, 4, 0, 0, 4, 3, 2, 4, 0, 0, 2, 4, 4, 0, 3, 4, 0, 6,
       6, 4, 2, 4, 0, 3, 3, 3, 0, 0, 5, 3, 4, 4, 7, 0, 6, 2, 0, 2, 0, 0,
       1, 4, 2, 4, 4, 0, 6, 2, 0, 4, 7, 4, 0, 6, 0, 0, 7, 7, 0, 0, 0, 0,
       0, 4, 0, 4, 0, 4, 0, 0, 0, 0, 2, 4, 4, 0, 3, 0, 0, 4, 2, 0, 0, 0,
       0, 3, 0, 4, 3, 0, 6, 2, 3, 4, 4, 4, 4, 4, 0, 2, 0, 3, 0, 0, 0, 3,
       0, 7, 0, 0, 0, 2, 4, 7, 0, 0, 3, 2, 0, 0, 5, 3, 4, 4, 0, 0, 3, 3,
       5, 4, 0, 0, 7, 4, 0, 3, 2, 0, 0, 4, 2, 0, 3, 2, 3, 0, 0, 5, 6, 0,
       0, 0, 0, 4, 6, 2, 0, 1, 4, 4, 3, 3, 0, 0, 3, 5, 0, 0, 0, 4, 6, 4,
       3, 1, 0, 2, 2, 4, 4, 4, 0, 3, 2, 3, 6, 1, 0, 0, 0, 3, 1, 4, 0, 6,
       4, 4, 7, 3, 4, 0, 4, 1, 0, 1, 0, 3, 0, 1, 3, 2, 0, 0, 0, 7, 0, 7,
       2, 0, 7, 0, 3, 4, 4, 0, 0, 0, 4, 7, 0, 4, 0, 3, 0, 7, 0, 0, 3, 0,
       7, 3, 0, 4, 3, 0, 0, 2, 7, 0, 6, 0, 3, 0, 2, 0, 2, 7, 3, 4, 7, 7,
       0, 4, 0, 0, 0, 0, 0, 4, 3, 0, 4, 3, 0, 7, 4,